spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/flyernetwork
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    servlet:
      path: /flyercore

amazonProperties:
  endpointUrl: https://s3.sa-east-1.amazonaws.com
  accessKey: AKIA3HHQ3SN5Z3U5CEH7
  secretKey: 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
  bucketName: tulio-buck01

