spring:
    mvc:
        servlet:
            path: /flyercore
    data:
        rest:
            detection-strategy: annotated
        mongodb:
            database: flyernetwork
            uri: mongodb://admin:admin@localhost:27017/?authSource=admin

